### ISSUE TITLE
Adjust scroll speed?

### ISSUE THREAD

**Issue by gurinderhans** [Kazark/vim-SimpleSmoothScroll#3]
I find the default speed still a bit fast, can we set options to decrease the speed?

**Comment by Kazark** [comment]
Sure, shouldn't be too hard. If I get a chance I can look at it, or feel free to send me a PR.

**Comment by gurinderhans** [comment]
Ah I've been looking at the source and tried a few things, but with no luck.

I wanted to adjust the speed for the trackpad / mouse scroll. Is that even possible?

Because all you do is map the mouse scroll events to <C-Y> and <C-E>, the function only runs for <C-D> and <C-U>

**Comment by Kazark** [comment]
The key is to adjust the number of milliseconds passed to `:sleep`.

**Comment by gurinderhans** [comment]
sorry forgot to escape angle brackets in the last comment, I meant to say the Scroll function only runs for \<C-D\> and \<C-U\> and not the mouse scroll. Adjusting the milliseconds to `:sleep` would only have effect if that function ran for the mouse scroll, which it doesnt.

**Comment by Kazark** [comment]
Closed by @verylazyguy in #6 .
